name: ml_framework_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - scipy
  - protobuf
  - paramiko
  - pip:
      - skl2onnx
      - tf2onnx
      - scikit-learn
      - tensorflow==2.17.0
      - onnx
      - onnxruntime
      - xgboost
      - lightgbm
      - tensorflow-model-optimization
      - catboost
      - torch