name: ml_framework_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - skl2onnx
      - tf2onnx
      - scikit-learn
      - tensorflow
      - onnx
      - onnxruntime
      - xgboost
      - lightgbm
      - tensorflow-model-optimization
      - sklearn
      - catboost
      - torch